
const name = [
    "Sora",
    "Taiyo",
    "Akira",
    "Mori",
    "Kaito",
    "Touma",
    "Daichi",
    "Ahmya",
    "Midori",
    "Moriko",
    "Jin",
    "Shun",
    "Misaye",
    "Momo",
    "Nanami",
    "Ginjiro",
    "Giichi",
    "Mizu",
    "Raiden",
    "Rikuto",
    "Ronin",
    "Mamoru",
    "Tadashi",
    "Taiki",
    "Tomohiro",
    "Isoko",
    "Itsuki",
    "Kairi",
    "Kin",
    "Maho",
    "Mirai",
    "Muga",
    "Riki",
    "Ryuosuke",
    "Long",
    "Tiên",
    "Tuyết",
    "Hải",
    "Minh",
    "Trai",
    "Châu",
    "Ngoc",
    "Vân",
    "Thuy",
    "Am",
    "Nguyêt",
    "Sen",
    "Mùchén",
    "Hàoyǔ",
    "Yìchén",
    "Ruòxī",
    "Caihong",
    "Kun",
    "Meilin",
    "Yawen",
    "Hai",
    "Qiang",
    "Xiang",
    "Yuze",
    "Jin",
    "Kong",
    "Lai",
    "Galatea",
    "Callisto",
    "Hali",
    "Aelius",
    "Alcyone",
    "Siren",
    "Triton",
    "Aster",
    "Geo",
    "Luna",
    "Celeste",
    "Adamaris",
    "Clara",
    "Elysia",
    "Mirai",
    "Marina",
    "Aurelius",
    "Miles",
    "Nero",
    "Nova",
    "Pluto",
    "Aqua",
    "Juniper",
    "Onyx",
    "Terra",
    "Delmar",
    "Caspian",
    "Amaranta",
    "Cielo",
    "Nube",
    "Sol",
    "Lluvia",
    "Tierra",
    "Aalto",
    "Hurley",
    "Llyr",
    "Morgan",
    "Heli",
    "Cordelia",
    "Guienevere",
    "Morwenna",
    "Murial",
    "Murray",
    "Nixie",
    "Moira",
    "Tarni",
    "Vanora",
    "Douglass",
    "Malik",
    "Suriya",
    "Harnav",
    "Anav",
    "Anik",
    "Arun",
    "Kai",
    "Arbaz",
    "Eshan",
    "Ishaan",
    "Jiyan",
    "Alam",
    "Sahaj",
    "Nur",
    "Kartika",
    "Dewi",
    "Bayu",
    "Bulan",
    "Mentari",
    "Banyu",
    "Mego",
    "Rimbo",
    "Satria",
    "Ningrum",
    "Harto",
    "Amir",
    "Amira",
    "Gemma",
    "Neve",
    "Vittoria",
    "Stella",
    "Luce",
    "Perla",
    "Fiamma",
    "Azzurra",
    "Futura",
    "Leonardo",
    "Galileo",
    "Ottone",
    "Rocco",
    "Antonio",
    "Mario",
    "Silvano",
    "Mare",
    "Candido",
    "Tiberius",
    "Sedna",
    "Bean",
    "Vita",
    "Neva",
    "More",
    "Rak",
    "Mir",
    "Sava",
    "Shuma",
    "Lipa",
    "Kamen",
    "Cvijet",
    "Posar",
    "Zrak",
    "Nebo",
    "Daniele",
    "Quân",
    "Khanh",
    "Bernice",
    "Isaac",
    "Lala",
    "Trang",
]
const adjective = [
    "wonderful",
    "hellish",
    "ill-fated",
    "callous",
    "grateful",
    "magical",
    "abnormal",
    "icy",
    "irate",
    "lamentable",
    "dead",
    "imaginary",
    "merciful",
    "obscene",
    "fair",
    "dazzling",
    "cultured",
    "bitter",
    "slim",
    "maddening",
    "lethal",
    "rebel",
    "axiomatic",
    "imaginary",
    "gainful",
    "momentous",
    "whimsical",
    "utopian",
    "unobtainable",
    "whispering",
    "ludicrious",
    "colorful",
    "mysterious",
    "electric",
    "surpreme",
    "capable",
    "steadfast",
    "passionate",
    "good",
    "broken",
    "angsty",
    "shiny",
    "unwell",
    "passionate",
    "sly",
    "sneaky",
    "stealthy",
    "capable",
    "fearsome",
    "illuminating",
    "celestial",
    "submerssive",
    "inundated",
    "Bright",
    "luminour",
    "rich",
    "sunny",
    "clear",
    "flourescent",
    "glossy",
    "glowing",
    "polished",
    "shining",
    "ablaze",
    "aglow",
    "cloudless",
    "lambent",
    "lucent",
    "lustrous",
    "radiant",
    "resplendent",
    "scintillant",
    "unobscured",
    "vivid",
    "flaming",
    "frozen",
    "earthly",
    "cold",
    "merciless",
    "cunning",
    "astute",
    "rancorous",
    "elevated",
    "astounding",
    "magnificent",
    "cursed",
    "bubbly",
    "cool",
    "untamed",
    "bothered",
    "clandestine",
    "nowhere",
    "universal",
    "enigmatic",
    "surreptitious",
    "sly",
    "wily",
    "silent",
    "magnificent",
    "miraculous",
    "stupendous",
    "phenomenal",
    "brilliant",
    "incredible",
    "wonderous",
    "holy",
]
const noun = [
    "sprite",
    "zoea",
    "wizard",
    "spirit",
    "soul",
    "mecha",
    "rider",
    "warrior",
    "general",
    "knave",
    "king",
    "undead",
    "ghost",
    "shimmer",
    "collector",
    "muse",
    "hermit",
    "wanderer",
    "mirth maker",
    "crook",
    "gangs",
    "defender",
    "nightmare",
    "soothsayer",
    "siren",
    "solider",
    "fighter",
    "trainer",
    "pawn",
    "knight",
    "guardian",
    "champion",
    "hero",
    "conqueror",
    "master",
    "creator",
    "weirdo",
    "guide",
    "advisor",
    "commander",
    "trickster",
    "jester",
    "colonel",
    "crabling",
    "robot",
    "bubble",
    "nobody",
    "entity",
    "victor",
    "blob",
    "wayfarer",
    "being",
]
const place = [
    "Cloud Mountains",
    "Celestial Citadel",
    "Sky Forest",
    "Azure Heavens",
    "Celestial Sphere",
    "Vault of Heaven",
    "Clay terrain",
    "Dry valleys",
    "Briny deep",
    "High seas",
    "Upper tides",
    "Seaweed forest",
    "Bubble city",
    "Kelp forests",
    "Seagrass Meadows",
    "Coral Reefs",
    "Oyster Reefs",
    "Rainbow Bridge",
    "Rainbow Cove",
    "Dark Caverns",
    "Grasslands",
    "Glacial Plains",
    "Teal Estuary",
    "Mountainous Desert",
    "The Hanging Sky Gardens",
    "Dragon Palace",
    "Elysium Fields",
    "Zerzura's Gates",
    "Cursed Isles",
    "Ghost Mountain",
    "Nymph Valley",
    "Catacombs of Cibola",
    "Outer Ocean Rift",
    "Glacial City",
    "Moon Mountains",
    "Sea of Fallen Stars",
    "Silver City",
    "Glacial Woodlands",
    "Winter Spyre",
    "Frozen Lakes",
    "Mechanical City",
    "Obscured City",
    "Clocktower",
    "Alchemic Empire",
    "Traction Town",
    "Steel City",
    "Quantum Gears",
    "Cyborg Caves",
    "Steam Highlands",
]

exports.getAnomuraName = (walletAddress = "") => {

    let rand = Math.round(Math.random());
    let namePart = name[Math.round(Math.random() * name.length)]
    let adjectivePart = adjective[Math.round(Math.random() * adjective.length)]
    let nounPart = noun[Math.round(Math.random() * noun.length)]
    let placePart = place[Math.round(Math.random() * place.length)]

    if (rand === 0) {
        return `${namePart} the ${adjectivePart} ${nounPart} of the ${placePart}`
    }
    else {
        return `${namePart} of the ${adjectivePart} ${placePart}`
    }

};